name: contentchef_dart
description: The headless CMS designed to accelerate the success of any digital experience. This is the client for any dart/flutter applications.
authors:
  - ContentChef Team <support@contentchef.io>
version: 1.0.0
homepage: https://www.contentchef.io
repository: https://github.com/dart-lang/http
documentation: https://docs.contentchef.io/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1

